station/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include(("trains.urls", "trains"), namespace="trains")),
#     # path('trains/', include(('trains.urls', 'trains'), namespace='trains')),

#     path('users/', include(('users.urls', 'users'), namespace="users")),
#     path('tickets/', include(('tickets.urls', 'tickets'), namespace='tickets')),
#     path('screenings/', include(('screenings.urls', 'screenings'), namespace='screenings'))
# ]


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('trains.urls', 'trains'), namespace='trains')),
    path('user/', include(('users.urls', 'users'), namespace='users')),
    path('tickets/', include(('tickets.urls', 'tickets'), namespace='tickets')),
    path('screenings/', include(('screenings.urls', 'screenings'), namespace='screenings'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tickets/urls.py
from django.urls import path
import tickets.views as views

urlpatterns = [
    path('buy/<int:screening_id>/', views.buy, name='buy'),
    path('<int:ticket_id>/', views.ticket_page, name='ticket_page')
]

trains/urls.py
from django.urls import path
import trains.views as views

urlpatterns = [
    path('', views.active_trains_list, name='index'),
    path('train/<int:train_id>/', views.train_page, name='train_page')
]

users/urls.py
from django.urls import path
import users.views as views

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout/', views.logout, name='logout')
]

trains/models.py
from django.db import models
from django.utils import timezone
from screenings.models import Screening

# Create your models here.


class Train(models.Model):
    title = models.CharField(max_length=32, null=False, blank=False)
    description_of_direction = models.TextField(null=False, blank=False)
    start_of_the_trip = models.DateField(null=False, blank=False, default=timezone.now)
    end_of_the_trip = models.DateField(null=False, blank=False, default=timezone.now)

    def __str__(self):
        return f'{self.title}'

    def get_sessions_count(self):
        return Screening.objects.filter(poezd_id__id=self.id).filter(time__gt=timezone.now()).count()

trains/views.py
from django.shortcuts import render
from trains.models import Train
from django.http import Http404

# App services
from trains.services.get_current_and_next_trains import get_current_and_next_trains


# Create your views here.

def active_trains_list(request):
    context = dict()
    context['current_trains'], context['next_trains'] = get_current_and_next_trains()
    return render(request, 'trains/active_list.html', context)


def train_page(request, train_id):
    try:
        train = Train.objects.get(id=train_id)
        return render(request, 'trains/train_page.html', {'train': train})
    except Train.DoesNotExist:
        raise Http404

templates/trains/active_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Поезда
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/trains/active_list.css' %}">
{% endblock %}

{% block content %}
    <h1 class="color-title">ВЫБЕРИТЕ МАРШРУТ</h1>
    <div class="train-container">
    <!-- <div class="train-container-new"> -->
    <!-- {% if next_trains %}
        {% for train in next_trains %}
            <p class="train-title">{{ train.title }}</p>
            <a href="{% url 'trains:train_page' train_id=train.id %}" class="button">Подробнее</a>
            <a href="{% url 'tickets:buy' screening_id=train.id %}" class="button movie-buy-button">Купить билет</a>
        {% endfor %}
    {% else %}     -->
        <!-- <p>Нет актуальных направлений</p> -->

        <div class="train-row">
            <img class="train-ticket-image" src="/media/trains-img/Peter.jpg" alt="poster">
            <p class="train-title">Тула - Санкт-Петербург</p>
            <div>
                <a href="{% url 'trains:train_page' train_id=2 %}" class="button">Подробнее</a>
                <a href="{% url 'tickets:buy' screening_id=2 %}" class="button movie-buy-button button-distance">Купить билет</a>
            </div>
        </div>

        <div class="train-row">
            <img class="train-ticket-image" src="/media/trains-img/Vldk.jpeg" alt="poster">
            <p class="train-title">Тула - Владикавказ</p>
            <div class="distance-2">
                <a href="{% url 'trains:train_page' train_id=3 %}" class="button">Подробнее</a>
                <a href="{% url 'tickets:buy' screening_id=3 %}" class="button movie-buy-button button-distance">Купить билет</a>
            </div>
        </div>

        <div class="train-row">
            <img class="train-ticket-image" src="/media/trains-img/Bel.jpeg" alt="poster">
            <p class="train-title">Тула - Белгород</p>
            <div class="distance-3">
                <a href="{% url 'trains:train_page' train_id=8 %}" class="button">Подробнее</a>
                <a href="{% url 'tickets:buy' screening_id=10 %}" class="button movie-buy-button button-distance">Купить билет</a>
            </div>
        </div>

        <div class="train-row">
            <img class="train-ticket-image" src="/media/trains-img/Mo.jpeg" alt="poster">
            <p class="train-title">Тула - Москва</p>
            <div class="distance">
                <a href="{% url 'trains:train_page' train_id=1 %}" class="button">Подробнее</a>
                <a href="{% url 'tickets:buy' screening_id=1 %}" class="button movie-buy-button button-distance">Купить билет</a>
            </div>
        </div>

        <div class="train-row">
            <img class="train-ticket-image" src="/media/trains-img/Mi.jpeg" alt="poster">
            <p class="train-title">Тула - Минск</p>
            <div class="distance-4">
                <a href="{% url 'trains:train_page' train_id=9 %}" class="button">Подробнее</a>
                <a href="{% url 'tickets:buy' screening_id=11 %}" class="button movie-buy-button button-distance">Купить билет</a>
            </div>
        </div>
        
        

    {% endif %} 
    </div>

    

{% endblock %}

templates/trains/train_page.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/trains/train_page.css' %}">
{% endblock %}

{% block title %}
	{{ train.title }}
{% endblock %}

{% block content %}
    <div class="train-container">
        <div>
            <div class="train-title-container">
                <h1>{{ train.title }}</h1>
            </div>
            <div class="train-fields-container">
                <p class="train-description">{{ train.description_of_direction }}</p>
                <a href="{% url 'tickets:buy' screening_id=train.id %}" class="button train-buy-button">Купить билет</a>
            </div>
        </div>
    </div>
{% endblock %}