screenings/urls.py
from django.urls import path
import screenings.views as views

urlpatterns = [
    path('schedule/', views.screenings_schedule, name='schedule'),
    path('schedule/<int:train>/', views.movie_screenings_schedule, name='train_schedule')
]

station/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include(("trains.urls", "trains"), namespace="trains")),
#     # path('trains/', include(('trains.urls', 'trains'), namespace='trains')),

#     path('users/', include(('users.urls', 'users'), namespace="users")),
#     path('tickets/', include(('tickets.urls', 'tickets'), namespace='tickets')),
#     path('screenings/', include(('screenings.urls', 'screenings'), namespace='screenings'))
# ]


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('trains.urls', 'trains'), namespace='trains')),
    path('user/', include(('users.urls', 'users'), namespace='users')),
    path('tickets/', include(('tickets.urls', 'tickets'), namespace='tickets')),
    path('screenings/', include(('screenings.urls', 'screenings'), namespace='screenings'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trains/urls.py
from django.urls import path
import trains.views as views

urlpatterns = [
    path('', views.active_trains_list, name='index'),
    path('train/<int:train_id>/', views.train_page, name='train_page')
]

users/urls.py
from django.urls import path
import users.views as views

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout/', views.logout, name='logout')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} - Station</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300..700&family=Inter:wght@100..900&display=swap" rel="stylesheet">
    {% block style %}{% endblock %}
</head>
<body>
    <header class="base-header">
        <div class="base-header-left">
            <div class="base-logo-container">
            <p class="base-title">ЖЕЛЕЗНОДОРОЖНЫЙ ВОКЗАЛ</p>
        </div>
        <nav>
            <ul class="base-nav">
                <li><a href="{% url 'trains:index' %}" 
                   {% if request.path == '/' %}
                    class="base-active-link"
                   {% else %}
                    class="base-header-link"
                   {% endif %}
                >Поезда и маршруты</a></li>
                <!-- <li><a href="{% url 'screenings:schedule' %}" 
                   {% if request.path == '/screenings/schedule/' %}
                    class="base-active-link"
                   {% else %}
                    class="base-header-link"
                   {% endif %}
                >Расписание</a></li> -->
            </ul>
        </nav>
        </div>
        <div class="base-user-container">
            {% if request.user.is_authenticated %}
            	<a href="{% url 'users:profile' %}" 
                   {% if request.path == '/user/profile/' %}
                    class="base-active-link"
                   {% else %}
                    class="base-header-link"
                   {% endif %}
                >Профиль</a>
                <a class="base-header-link" href="{% url 'users:logout' %}">Выйти</a>
            {% else %}
                <a class="base-header-link" href="{% url 'users:login' %}">Войти</a>
            {% endif %}
        </div>
    </header>
    <main class="main-fon">
    <div class="base-content-container">
        {% block content %}{% endblock %}
    </div>

    
    </main>
    <footer class="base-footer">
        <nav>
            <ul class="base-footer-nav-container">
                <li><a href="https://www.rzd.ru/" target="_blank"
                   {% if request.path == '/' %}
                    class="base-active-link"
                   {% else %}
                    class="base-header-link"
                   {% endif %}
                >https://www.rzd.ru/</a></li>
                <li><p 
                   {% if request.path == '/screenings/schedule/' %}
                    class="base-active-link"
                   {% else %}
                    class="base-header-link"
                   {% endif %}
                >+7(4872)20-25-97</p></li>
            </ul>
        </nav>
    </footer>
</body>
</html>