station/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include(("trains.urls", "trains"), namespace="trains")),
#     # path('trains/', include(('trains.urls', 'trains'), namespace='trains')),

#     path('users/', include(('users.urls', 'users'), namespace="users")),
#     path('tickets/', include(('tickets.urls', 'tickets'), namespace='tickets')),
#     path('screenings/', include(('screenings.urls', 'screenings'), namespace='screenings'))
# ]


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('trains.urls', 'trains'), namespace='trains')),
    path('user/', include(('users.urls', 'users'), namespace='users')),
    path('tickets/', include(('tickets.urls', 'tickets'), namespace='tickets')),
    path('screenings/', include(('screenings.urls', 'screenings'), namespace='screenings'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tickets/urls.py
from django.urls import path
import tickets.views as views

urlpatterns = [
    path('buy/<int:screening_id>/', views.buy, name='buy'),
    path('<int:ticket_id>/', views.ticket_page, name='ticket_page')
]

users/urls.py
from django.urls import path
import users.views as views

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout/', views.logout, name='logout')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    image = models.ImageField(upload_to="users-images", blank=True, null=True)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Введите имя пользователя'}
    )
    )
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Введите пароль'
        }
    ))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Введите имя пользователя'
        }
    ))

    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Введите имя'
        }
    ))

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Введите фамилию'
        }
    ))

    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'placeholder': 'Введите адрес эл. почты'
        }
    ))

    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Введите пароль'
        }
    ))

    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Подтвердите пароль'
        }
    ))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Введите имя пользователя',
            'readonly': True
        }
    ))

    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Введите имя'
        }
    ))

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Введите фамилию'
        }
    ))

    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'placeholder': 'Введите адрес эл. почты'
        }
    ))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# App services
from users.services.update_user_profile import update_user_profile
from users.services.logout_user import logout_user
from users.services.login_user import login_user
from users.services.register_new_user import register_new_user
from tickets.services.get_user_tickets import get_user_tickets


@login_required(login_url='users:login')
def profile(request):
    if request.method == 'POST':
        return update_user_profile(user=request.user, data=request.POST)

    context = {
        'form': UserProfileForm(instance=request.user),
        'tickets': get_user_tickets(request.user),
    }

    return render(request, 'users/profile.html', context)


def logout(request):
    return logout_user(request)


def login(request):
    if request.method == 'POST':
        return login_user(request)
    else:
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('users:profile'))
        else:
            form = UserLoginForm()
    return render(request, 'users/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        return register_new_user(request)

    context = {'form': UserRegistrationForm()}

    return render(request, 'users/register.html', context)

templates/users/form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} - Station</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/users/form.css' %}">
    {% block style %}{% endblock %}
</head>
<body>
    <div class="base-container">
        <div class="base-logo-container">
                <p class="base-title">Ж/д вокзал Тула</p>
            </div>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/users/login.html
{% extends 'users/form.html' %}

{% block title %}
	Авторизация
{% endblock %}

{% block content %}
    <h1>Авторизация</h1>
    <div class="message">
            {% if messages or form.non_field_errors %}
                <div class="alert" id="alert">
                    <p class="alert-text">
                       {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% else %}
                        {{ form.non_field_errors }}
                    {% endif %} 
                    </p>
                        <button type="button" id="close" class="close" data-dismiss="alert" aria-label="Close">
                            <span>&times;</span>
                        </button>
                    </div>
            {% endif %}
        </div>
    <form class='auth-form' action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="auth-form-field">
            <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
            {{ form.username }}
        </div>
        <div class="auth-form-field">
            <label for="{{ form.password.id_for_label }}">Пароль</label>
            {{ form.password }}
        </div>
        <input class="btn btn-primary" type="submit" value="Войти">
        <a style="text-align: center" href="{% url 'users:register' %}">Зарегистрироваться</a>
    </form>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Профиль
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/users/profile.css' %}">
{% endblock %}

{% block content %}
    <div class="profile-container">
        <form action="{% url 'users:profile' %}" method="post" class="profile-form">
            <h1>Профиль</h1>
            {% csrf_token %}
            <div class="profile-form-field">
                <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
                {{ form.username }}
            </div>
            <div class="profile-form-field">
                <label for="{{ form.first_name.id_for_label }}">Имя</label>
                {{ form.first_name }}
            </div>
            <div class="profile-form-field">
                <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
                {{ form.last_name }}
            </div>
            <div class="profile-form-field">
                <label for="{{ form.email.id_for_label }}">E-mail</label>
                {{ form.email }}
            </div>
            <input class="btn btn-primary" type="submit" value="Сохранить">
        </form>
        <div class="profile-tickets-container">
            <h1>Билеты</h1>
        {% if tickets %}
            {% for ticket in tickets %}
            <div class="profile-ticket">
                <div>
                    <img class="profile-ticket-image" src="/media/trains-img/icon-new.avif" alt="poster">
                    <div class="profile-ticket-text">
                        <p class="profile-ticket-title">{{ ticket.screening.poezd_id.title }}</p>
                        <div class="profile-ticket-info">
                            <div>
                               <p>{{ ticket.screening.time|date:"j E"}} </p>
                                <p>{{ ticket.screening.time|date:"H:i"}}</p>
                                <p>{{ ticket.screening.poezd_id.age_restriction}}</p>
                            </div>
                            <div>
                                {{ ticket.screening.carriage }} вагон {{ ticket.place }} купе {{ ticket.row }} место
                            </div>
                        </div>
                    </div> 
                </div>
                <a href='{% url "tickets:ticket_page" ticket_id=ticket.id %}' class="button">Открыть</a>
            </div>
            {% endfor %}
        {% else %}
        <p>Пока пусто</p>
        {% endif %}
        </div>
    </div>

{% endblock %}

templates/users/register.html
{% extends 'users/form.html' %}

{% block title %}
	Регистрация
{% endblock %}

{% block content %}
    <h1>Регистрация</h1>
    <div>
        <div class="message">
            {% if messages or form.non_field_errors %}
                <div class="alert">
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% else %}
                        {{ form.non_field_errors }}
                    {% endif %}
                        <button type="button" class="close" id="close" data-dismiss="alert" aria-label="Close">
                            <span>&times;</span>
                        </button>
                    </div>
            {% endif %}
        </div>
    <form class='auth-form' action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <div class="auth-form-field">
            <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
            {{ form.username }}
        </div>
        <div class="auth-form-field">
            <label for="{{ form.first_name.id_for_label }}">Имя</label>
            {{ form.first_name }}
        </div>
        <div class="auth-form-field">
            <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
            {{ form.last_name }}
        </div>
        <div class="auth-form-field">
            <label for="{{ form.email.id_for_label }}">E-mail</label>
            {{ form.email }}
        </div>
        <div class="auth-form-field">
            <label for="{{ form.password1.id_for_label }}">Пароль</label>
            {{ form.password1 }}
        </div>
        <div class="auth-form-field">
            <label for="{{ form.password2.id_for_label }}">Подтвердите пароль</label>
            {{ form.password2 }}
        </div>
        <input type="submit" value="Зарегистрироваться">
        <a style="text-align: center" href="{% url 'users:login' %}">У меня уже есть аккаунт</a>
    </form>
    </div>
{% endblock %}